<<<<<<< Updated upstream
language: python
rvm:
script: python manage.py
=======
language:
  - python
before-install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
script:
  - flake8 --max-line-length=92
  - black .
>>>>>>> Stashed changes
after_success:
  - coveralls
