<<<<<<< Updated upstream
language: python
=======

language: python
script: python manage.py
language:
  - python
>>>>>>> Stashed changes
before-install:
  - pip install flake8
  - pip install black
  - pip install -r requirements.txt
script:
  - flake8 --max-line-length=92
<<<<<<< Updated upstream
  - black .
=======
  - black --check .
>>>>>>> Stashed changes
after_success:
  - coveralls
